"""initial

Revision ID: 0001
Revises:
Create Date: 2026-09-19 12:54:50.876334

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("rel_path", sa.String(), nullable=False),
        sa.Column("mime", sa.String(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("compliant", sa.Boolean(), nullable=True),
        sa.Column("compliance_report_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('raw', 'final', 'reference', 'preview')", name=op.f("ck_asset_ck_asset_kind")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset")),
        sa.UniqueConstraint("sha256", name=op.f("uq_asset_sha256")),
    )
    op.create_table(
        "channel",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("youtube_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("fetched_at", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint("source IN ('ytdlp', 'api')", name=op.f("ck_channel_ck_channel_source")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel")),
        sa.UniqueConstraint("youtube_id", name=op.f("uq_channel_youtube_id")),
    )
    op.create_table(
        "provider_profile",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("provider_key", sa.String(), nullable=False),
        sa.Column("provider_version", sa.String(), nullable=False),
        sa.Column("params_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_profile")),
        sa.UniqueConstraint("name", name=op.f("uq_provider_profile_name")),
    )
    op.create_table(
        "template",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("prompt_template", sa.Text(), nullable=False),
        sa.Column("layout_spec_json", sa.Text(), nullable=False),
        sa.Column("spec_hash", sa.String(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template")),
        sa.UniqueConstraint("name", "version", name="uq_template_name_version"),
    )
    op.create_table(
        "playlist",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("youtube_id", sa.String(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("fetched_at", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
            name=op.f("fk_playlist_channel_id_channel"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playlist")),
        sa.UniqueConstraint("youtube_id", name=op.f("uq_playlist_youtube_id")),
    )
    op.create_table(
        "video",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("youtube_id", sa.String(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("duration_s", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("source_thumbnail_url", sa.String(), nullable=True),
        sa.Column("fetched_at", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
            name=op.f("fk_video_channel_id_channel"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video")),
        sa.UniqueConstraint("youtube_id", name=op.f("uq_video_youtube_id")),
    )
    op.create_table(
        "playlist_item",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("playlist_id", sa.String(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("part_number", sa.Integer(), nullable=True),
        sa.Column("part_label", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlist.id"],
            name=op.f("fk_playlist_item_playlist_id_playlist"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video.id"],
            name=op.f("fk_playlist_item_video_id_video"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playlist_item")),
        sa.UniqueConstraint("playlist_id", "position", name="uq_playlist_item_playlist_position"),
        sa.UniqueConstraint("playlist_id", "video_id", name="uq_playlist_item_playlist_video"),
    )
    op.create_table(
        "run",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("template_id", sa.String(), nullable=False),
        sa.Column("provider_profile_id", sa.String(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=True),
        sa.Column("playlist_id", sa.String(), nullable=True),
        sa.Column("reference_asset_id", sa.String(), nullable=True),
        sa.Column("parent_run_id", sa.String(), nullable=True),
        sa.Column("params_json", sa.Text(), nullable=False),
        sa.Column("started_at", sa.String(), nullable=True),
        sa.Column("finished_at", sa.String(), nullable=True),
        sa.Column("error_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint("kind IN ('hero', 'iterate', 'batch')", name=op.f("ck_run_ck_run_kind")),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'paused', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_run_ck_run_status"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_run_id"],
            ["run.id"],
            name=op.f("fk_run_parent_run_id_run"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlist.id"],
            name=op.f("fk_run_playlist_id_playlist"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_profile_id"],
            ["provider_profile.id"],
            name=op.f("fk_run_provider_profile_id_provider_profile"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reference_asset_id"],
            ["asset.id"],
            name=op.f("fk_run_reference_asset_id_asset"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["template.id"],
            name=op.f("fk_run_template_id_template"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["video.id"], name=op.f("fk_run_video_id_video"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run")),
    )
    op.create_table(
        "iteration",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("raw_asset_id", sa.String(), nullable=True),
        sa.Column("final_asset_id", sa.String(), nullable=True),
        sa.Column("picked", sa.Boolean(), nullable=False),
        sa.Column("provider_request_json", sa.Text(), nullable=False),
        sa.Column("provider_response_json", sa.Text(), nullable=False),
        sa.Column("started_at", sa.String(), nullable=True),
        sa.Column("finished_at", sa.String(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("cost_json", sa.Text(), nullable=True),
        sa.Column("error_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'paused', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_iteration_ck_iteration_status"),
        ),
        sa.ForeignKeyConstraint(
            ["final_asset_id"],
            ["asset.id"],
            name=op.f("fk_iteration_final_asset_id_asset"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["raw_asset_id"],
            ["asset.id"],
            name=op.f("fk_iteration_raw_asset_id_asset"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["run.id"], name=op.f("fk_iteration_run_id_run"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video.id"],
            name=op.f("fk_iteration_video_id_video"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_iteration")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_iteration_idempotency_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("iteration")
    op.drop_table("run")
    op.drop_table("playlist_item")
    op.drop_table("video")
    op.drop_table("playlist")
    op.drop_table("template")
    op.drop_table("provider_profile")
    op.drop_table("channel")
    op.drop_table("asset")
    # ### end Alembic commands ###
