"""The slice of uharfbuzz that `thumbforge.imaging.shaping` uses; the package ships no stubs."""

class Blob:
    def __init__(self, data: bytes | None = None) -> None: ...

class Face:
    def __init__(self, blob: Blob | None = None, index: int = 0) -> None: ...
    @property
    def upem(self) -> int: ...

class Font:
    def __init__(self, face: Face) -> None: ...
    def get_nominal_glyph(self, unicode: int) -> int | None: ...

class GlyphInfo:
    @property
    def codepoint(self) -> int: ...

class GlyphPosition:
    @property
    def x_advance(self) -> int: ...
    @property
    def x_offset(self) -> int: ...
    @property
    def y_offset(self) -> int: ...

class Buffer:
    def __init__(self) -> None: ...
    def add_str(self, text: str, item_offset: int = 0, item_length: int = -1) -> None: ...
    direction: str
    script: str
    language: str
    @property
    def glyph_infos(self) -> list[GlyphInfo]: ...
    @property
    def glyph_positions(self) -> list[GlyphPosition]: ...

def shape(
    font: Font,
    buffer: Buffer,
    features: dict[str, bool] | None = None,
    shapers: list[str] | None = None,
) -> None: ...
