"""Unit tests for Alembic migrations and drift detection (ADR 0004, Phase 1 spec)."""

from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import command
from sqlalchemy import inspect

from thumbforge.storage.db import _alembic_config, get_engine

if TYPE_CHECKING:
    from pathlib import Path


def test_migrations_upgrade_and_downgrade(tmp_path: Path) -> None:
    db_file = tmp_path / "migration_cycle.sqlite3"
    cfg = _alembic_config(db_file)

    # 1. Upgrade to head
    command.upgrade(cfg, "head")
    engine = get_engine(db_file)
    try:
        inspector = inspect(engine)
        tables_after_upgrade = set(inspector.get_table_names())
        expected_tables = {
            "alembic_version",
            "asset",
            "channel",
            "playlist",
            "video",
            "playlist_item",
            "template",
            "provider_profile",
            "run",
            "iteration",
        }
        assert expected_tables.issubset(tables_after_upgrade)
    finally:
        engine.dispose()

    # 2. Downgrade to base
    command.downgrade(cfg, "base")
    engine = get_engine(db_file)
    try:
        inspector = inspect(engine)
        tables_after_downgrade = set(inspector.get_table_names())
        assert "asset" not in tables_after_downgrade
        assert "channel" not in tables_after_downgrade
        assert "run" not in tables_after_downgrade
    finally:
        engine.dispose()

    # 3. Upgrade back to head
    command.upgrade(cfg, "head")
    engine = get_engine(db_file)
    try:
        inspector = inspect(engine)
        tables_final = set(inspector.get_table_names())
        assert expected_tables.issubset(tables_final)
    finally:
        engine.dispose()


def test_alembic_check_no_drift(tmp_path: Path) -> None:
    """CI gate: assert alembic check reports no drift between ORM models and migrations."""
    db_file = tmp_path / "check_drift.sqlite3"
    cfg = _alembic_config(db_file)

    command.upgrade(cfg, "head")
    # command.check raises AutogenerateDiffsDetected if models differ from DB schema
    command.check(cfg)
